- name: Creating Endpoint for cinder
  environment: admin_openrc_env
  command: "{{item}}"
  with_items:
  - openstack endpoint create --region RegionOne volume public http://controller:8776/v1/%\(tenant_id\)s
  - openstack endpoint create --region RegionOne volume internal http://controller:8776/v1/%\(tenant_id\)s
  - openstack endpoint create --region RegionOne volume admin http://controller:8776/v1/%\(tenant_id\)s
  - openstack endpoint create --region RegionOne volumev2 public http://controller:8776/v2/%\(tenant_id\)s
  - openstack endpoint create --region RegionOne volumev2 internal http://controller:8776/v2/%\(tenant_id\)s
  - openstack endpoint create --region RegionOne volumev2 admin http://controller:8776/v2/%\(tenant_id\)s
  register: cinder_endpoint_ready
