---
- name: install nova with kvm related packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - nova-compute
  when: {{ NOVA_VIRT_TYPE }} in ['kvm', 'qemu']

- name: install nova with lxc related packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - nova-compute-lxc
  when: 'lxc' == {{ NOVA_VIRT_TYPE }}

- name: update nova conf
  template: src=nova.conf dest=/etc/nova/nova.conf backup=yes
  notify:
    - restart nova-compute

- name: create nova-compute.conf
  template: src=nova-compute.conf dest=/etc/nova/nova-compute.conf backup=yes

- name: nova compute restart
  service: name=nova-compute state=restarted

- meta: flush_handlers
