---
- name: install mysql client and server packages
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mariadb-server

- name: create mysqld_openstack.cnf
  template: src=mysqld_openstack.cnf
        dest=/etc/mysql/conf.d/mysqld_openstack.cnf
        backup=yes
  notify:
    - restart mysql

- name: manually restart mysql server first before creating db models
  service: name=mysql
           state=restarted

# keystone
- name: create keystone db model
  mysql_db: name=keystone
            state=present

- name: create keystone local user
  mysql_user: name=keystone
              password={{ KEYSTONE_DBPASS }}
              priv=keystone.*:ALL
              state=present

- name: create keystone remote user
  mysql_user: host=%
              name=keystone
              password={{ KEYSTONE_DBPASS }}
              priv=keystone.*:ALL
              state=present

# glance
- name: create glance database
  mysql_db: name=glance
            state=present

- name: create glance local user
  mysql_user: name=glance
              password={{ GLANCE_DBPASS }}
              priv=glance.*:ALL
              state=present

- name: create glance remote user
  mysql_user: host=%
              name=glance
              password={{ GLANCE_DBPASS }}
              priv=glance.*:ALL
              state=present

# neutron
- name: create neutron database
  mysql_db: name=neutron
            state=present

- name: create neutron local user
  mysql_user: name=neutron
              password={{ NEUTRON_DBPASS }}
              priv=neutron.*:ALL
              state=present

- name: create neutron remote user
  mysql_user: host=%
              name=neutron
              password={{ NEUTRON_DBPASS }}
              priv=neutron.*:ALL
              state=present

# nova
- name: create nova database
  mysql_db: name=nova
            state=present

# nova-api
- name: create nova_api database
  mysql_db: name=nova_api
            state=present

- name: create nova local user
  mysql_user: name=nova
              password={{ NOVA_DBPASS }}
              append_privs=yes
              state=present
              priv={{ item }}
  with_items:
   - 'nova_api.*:ALL'
   - 'nova.*:ALL'

- name: create nova remote user
  mysql_user: host=%
              name=nova
              password={{ NOVA_DBPASS }}
              append_privs=yes
              state=present
              priv={{ item }}
  with_items:
   - 'nova_api.*:ALL'
   - 'nova.*:ALL'
