- name: Creating Services
  environment: TOKEN_ENV
  command: "{{item}}"
  with_items:
  - openstack service create --name keystone --description "OpenStack Identity" identity
  - openstack service create --name glance --description "OpenStack Image service" image
  - openstack service create --name nova --description "OpenStack Compute" compute
  - openstack service create --name neutron --description "OpenStack Networking" network
  #- openstack service create --name cinder --description "OpenStack Block Storage" volume
  #- openstack service create --name heat --description "Orchestration" orchestration
  #- openstack service create --name heat-cfn --description "Orchestration"  cloudformation
  #- openstack service create --name swift --description "Swift Service" object-store
  #- openstack service create --name ceilometer --description "OpenStack Metering Service" metering
  register: openstack_srvc_ready
